---
name: Appscms
title: Appscms - CMS for Mobile Apps
email: marketing@appscms.com
address: B404 Noida, 201301
phone: "8750348350"
tagline: Appscms - CMS for Mobile Apps
description: Appcms is a modern, cloud-based content & translation management system
  for all of your native mobile apps, enabling you to change strings in your app without
  Playstore release.
baseurl: ''
permalink: /blog/:categories/:year_:month_:day_:title
url: https://appscms.com
twitter_username: appscms
github_username: appscms
favicon: img/favicon.png
paginate: "12"
paginate_path: "/blog/page:num/"
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-include-cache
google_analytics: 'UA-179965937-1'
disqus:
  shortname: appscms-com
hero: product_fixed_image
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
whitelist:
- jekyll-sitemap
- jekyll-feed
- jekyll-include-cache
getform_id: 
mailchimp:
  user-id: 
  list-id: 
copyright_text: Copyright Â© 2020 All rights reserved to
company_url: https://appscms.com
google_site_verification: 
bing_site_verification: 
yandex_site_verification: 
naver_site_verification: 
twitter:
  username: 
facebook:
  username: 
  app_id: 
  publisher: 
og_image: 
social:
  type: 
  name: 
  links: 
analytics:
  provider: false
  google:
    tracking_id: 
    anonymize_ip: 
timezone: 
after: ruby hello.rb
